### ISSUE TITLE
Sku Selector on Shelf.

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#212] opened 2020-02-27 15:49 UTC
My last question was closed but the issue still persists. 
So please, give me some info before closing it again.

```json
{
  "shelf":{
    "blocks": ["product-summary.shelf"],
    "props": {
      "category": 1,
      "orderBy": "OrderByTopSaleDESC",
      "paginationDotsVisibility": "desktopOnly",
      "productList": {
          "maxItems": 8,
          "itemsPerPage": 5,
          "minItemsPerPage": 1,
          "scroll": "BY_PAGE",
          "arrows": true,
          "titleText": "Más Vendidos"
      },
      "skusFilter": "ALL_AVAILABLE"
  }
},
"product-summary.shelf": {
  "children": [
    "product-summary-image",
    "product-summary-add-to-list-button",
    "product-summary-name",
    "product-rating-inline",
    "product-summary-space",
    "product-summary-price",
    "product-identifier.summary",
    "product-summary-sku-selector",
    "product-summary-buy-button"
  ]
},
"product-summary-sku-selector": {
  "props":{
    "showVariationsLabels": ["false"]
  }
}
}
```

This is my actual shelf code. I've added the skusfilter with ALL_AVAILABLE as you've told me, but still, no sku-selector renders on my shelf. Just in my product page is working. 
I'm sorry I've reopened this issue but I really need to understand how this works since it's a must for my store.

Thanks.

**Comment by denisebiscaro** [comment] 2020-02-27 18:53
@EmperorPidgeon You have to add the specification names you want to show up in the prop visibleVariations on your product-summary-sku-selector component:
```
  "product-summary-sku-selector": {
    "props": {
      "visibleVariations" : ["color"]
    }
  },
```

In this case, you'll see only color variations on the SKU selector. The specification name should be the same as the one declared on your store's catalog.

We need to improve this documentation, though :(

**Comment by EmperorPidgeon** [comment] 2020-02-27 19:11
It's not doing anything. Tried with both Talle and Color which are my
specifications, nothing is showing up.

**Comment by Klynger** [comment] 2020-02-27 19:21
Something is happening that we don't know yet, so lets repopen the issue

**Comment by Klynger** [comment] 2020-02-27 20:50
@EmperorPidgeon could you send me a link with the theme linked?

**Comment by EmperorPidgeon** [comment] 2020-02-27 20:58
Zapatos--delucca.myvtex.com it's the one in using

**Comment by Klynger** [comment] 2020-02-28 14:08
@EmperorPidgeon I tried to reproduce, but I couldn't. This is the code of my `product-summary.shelf` block:

```json
{
"product-summary.shelf": {
    "children": [
      "stack-layout#prodsum",
      "product-summary-name",
      "product-rating-inline",
      "product-summary-space",
      "product-summary-price",
      "product-summary-sku-selector",
      "add-to-cart-button"
    ]
  }
}
```
I didn't add any customizatino or passed any props to the `product-summary-sku-selector` and it worked. So if you could share more information.

**Comment by EmperorPidgeon** [comment] 2020-02-28 14:19
I've tried your code without any customization in the
product-summary-sku-selector and still nothing it's showing, it's really
weird

**Comment by Klynger** [comment] 2020-02-28 18:37
What I saw in your workspace was that nothing was being rendered, it was like the component was returning `null` or something, nothign is shown in the React devtools

**Comment by EmperorPidgeon** [comment] 2020-02-28 18:40
But I just don't know what's going on, I've followed the guides and I've
got other workspace where it's working (ohter store) but in this one it
just doesn't appear.
Any idea on what could I try?

**Comment by Klynger** [comment] 2020-03-02 14:14
Are you sure you're using the `"product-summary.shelf"`? Maybe you're using something like `"product-summary#shelf"`, `"product-summary.shelf#something"`, or something like this.

**Comment by EmperorPidgeon** [comment] 2020-03-02 14:36
Hello, nope,I'm using product-summary.shelf

Here's the code:
{
  "shelf":{
      "blocks": ["product-summary.shelf"],
      "props": {
      "category": 1,
      "orderBy": "OrderByTopSaleDESC",
      "paginationDotsVisibility": "desktopOnly",
      "productList": {
          "maxItems": 8,
          "itemsPerPage": 5,
          "minItemsPerPage": 1,
          "scroll": "BY_PAGE",
          "arrows": true,
          "titleText": "Más Vendidos"
      }
  }
},
"product-summary.shelf": {
  "children": [
    "stack-layout#prodsum",
    "product-summary-name",
    "product-rating-inline",
    "product-summary-space",
    "product-summary-price",
    "product-summary-sku-selector",
    "add-to-cart-button"
  ]
}
}

**Comment by Klynger** [comment] 2020-03-03 15:01
I opened your repository again, this problem is happening because what you think is  a shelf, is not a shelf, is a `slider-layout`. So the `slider-layout` is rendering some different `product-summary`, you should look for `slider-layout` and see what block it is using. I'm going to close the issue now

**Comment by EmperorPidgeon** [comment] 2020-03-03 15:28
Hey, the home block with the slider-layout that contains a shelf has the
same properties.
So please, at least let me answer insted of closing the issue time after
time when it's never fixed.

{
  "store.home": {
    "blocks": [
      "list-context.image-list#demo",
      /* You can make references to blocks defined in other files.
       * For example, `flex-layout.row#deals` is defined in the
`deals.json` file. */
      "flex-layout.row#deals",
      "rich-text#shelf-title",
      "flex-layout.row#shelf",
      "rich-text#shelf-title2",
      "flex-layout.row#shelf2",
      "info-card#home",
      "newsletter"
    ]
  },

  "shelf#home": {
    "blocks": ["product-summary.shelf"],
    "props":{
      "skusFilter": "ALL_AVAILABLE",
      "visibleVariations" : ["Color"]
    }
  },
  "product-summary.shelf": {
    "children": [
      "stack-layout#prodsum",
      "product-summary-name",
      "product-rating-inline",
      "product-summary-space",
      "product-summary-price",
      "product-summary-sku-selector",
      "add-to-cart-button"
    ]
  },
  "list-context.image-list#demo": {
    "children": ["slider-layout#demo-images"],
    "props": {
      "height": 800,
      "images": [
        {
          "image": "
https://img.babathe.com/upload/specialDisplay/htmlImage/20200218_jigott_springcoupon_pc.jpg
",
          "mobileImage": "
https://storecomponents.vteximg.com.br/arquivos/banner-principal-mobile.jpg"
        },
        {
          "image": "
https://img.babathe.com/upload/specialDisplay/htmlImage/20200213_collection_office_look_pc2.jpg
",
          "mobileImage": "
https://storecomponents.vteximg.com.br/arquivos/banner-principal-mobile.jpg"
        }
      ]
    }
  },
  "slider-layout#demo-images": {
    "props": {
      "itemsPerPage": {
        "desktop": 1,
        "tablet": 1,
        "phone": 1
      },
      "infinite": true,
      "showNavigationArrows": "desktopOnly",
      "blockClass": "carousel"
    }
  },

  "rich-text#shelf-title": {
    "props": {
      "text": "## Verano 2020",
      "blockClass": "shelfTitle"
    }
  },
  "rich-text#shelf-title2": {
    "props": {
      "text": "## Más Vendidos",
      "blockClass": "shelfTitle"
    }
  },
  "flex-layout.row#shelf": {
    "children": ["list-context.product-list#demo1"]
  },
  "flex-layout.row#shelf2": {
    "children": ["list-context.product-list#demo1"]
  },
  "list-context.product-list#demo1": {
    "blocks": ["product-summary.shelf"],
    "children": ["slider-layout#demo-products"],
    "props": {
      "orderBy": "OrderByTopSaleDESC"
    }
  },
  "slider-layout#demo-products": {
    "props": {
      "itemsPerPage": {
        "desktop": 5,
        "tablet": 3,
        "phone": 2
      },
      "infinite": true,
      "fullWidth": false,
      "blockClass": "shelf"
    }
  },

  "info-card#home": {
    "props": {
      "id": "info-card-home",
      "isFullModeStyle": false,
      "textPosition": "left",
      "imageUrl": "
http://indiater.com/wp-content/uploads/2019/05/Promo-Summer-Collection-Fashion-Banner-Free-PSD-Template.jpg
",
      "headline": "Últimas Unidades",
      "callToActionText": "APROVECHALOS",
      "callToActionUrl": "/sale/d",
      "blockClass": "info-card-home",
      "textAlignment": "center"
    }
  },
  "newsletter":{
    "props":{
      "label": "Suscribite al Newsletter"
    }
  }
}

**Comment by klzns** [comment] 2020-03-03 17:05
@EmperorPidgeon can you check in your code if you have another `product-summary.shelf` declared in another file, please?

If you have another `product-summary.shelf` defined in another file this one might be overwriting this one.

**Comment by klzns** [comment] 2020-03-03 18:52
Btw, we just launched a change in our infrastructure to check for duplicate definitions of blocks that might avoid those kind of issues.

**Comment by EmperorPidgeon** [comment] 2020-03-04 12:47
Thanks a lot man. Finally got it working!
There was a duplicate in an unused block that was overriding this settings
I guess. I've erased it and now everything works fine.

**Comment by klzns** [comment] 2020-03-04 13:04
That's good to hear!

**Closed by klzns** 2020-03-04 13:04 UTC
Labels: question
