### ISSUE TITLE
Shelf product colors

### ISSUE THREAD

**Issue by rickarof** [vtex-apps/store-discussion#109] opened 2019-09-10 17:38 UTC
**Is your feature request related to a problem? Please describe.**
Our client requested a shelf that shows the product and its color variations, allowing the user to see/select the color options before accessing the product page.

**Describe the solution you'd like**
Make it possible to bring product along with it's color options, not sure if based on SKU variations or color specification, but this initial idea could be considered.

**Describe alternatives you've considered**
Couldn't find a way to do that properly

**Additional context**
Example:
![Captura de Tela 2019-09-10 às 13 58 48](https://user-images.githubusercontent.com/15057760/64635349-d665c780-d3d5-11e9-9b03-0c0d9d476ea5.png)

**Comment by klzns** [comment] 2019-09-10 17:44
Duplicate of https://github.com/vtex-apps/store-discussion/issues/17

**Closed by klzns** 2019-09-10 17:44 UTC
Labels: feature-request
