### ISSUE TITLE
Wrong sku when you select sku and add to cart too fast

### ISSUE THREAD

**Issue by IvanClementino** [vtex-apps/store-discussion#602] opened 2021-06-09 18:58 UTC
**Describe the bug**
If you change from one sku to another (pdp - sku-selector) and add the product to the cart too fast, it might add the old selection rather than the new one. Could reproduce on mobile and desktop. Some customers were able to do this a few times and complained about it.

**Comment by IvanClementino** [comment] 2021-06-09 19:18
Never mind the mitigation part. The issue still occurs when there is no sku selected.
If you select too fast and click to add to cart, the first sku will be added.
Also reproduced on desktop now.

**Comment by IvanClementino** [comment] 2021-06-09 19:20
Might a suggest a disabled+loading state for the add-to-cart button while the new sku is loaded?

**Comment by IvanClementino** [comment] 2021-06-11 20:40
@jpesce took the liberty to test this on oficinareserva and it also seems to suffer from this. Have you noticed it before?

**Comment by jpesce** [comment] 2021-06-11 20:49
Thanks very much @IvanClementino! I couldn't reproduce. When I click on another size, the “Add to Cart” button is inactivated temporarily and when it's available again it adds the correct size. Would you mind sharing a video showing the bug?

**Comment by IvanClementino** [comment] 2021-06-11 20:53
@jpesce here you go
https://user-images.githubusercontent.com/71457970/121747540-f01dcc80-cadd-11eb-8005-c75bb9c5e7db.mp4

**Comment by jpesce** [comment] 2021-06-11 21:00
@IvanClementino Thank you! I'll report this to them as well! Hopefully they'll act on it.

**Comment by IvanClementino** [comment] 2021-06-11 21:02
> @IvanClementino Thank you! I'll report this to them as well! Hopefully they'll act on it.
> 
> Are you using Linux? On my computer I can't reproduce this.
> 
> Can you post the output of the following command?
> 
> ```
> $ npx envinfo --system --binaries --browsers
> ```

Yeah, but also reproduced on android and iphone
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 AMD Ryzen 3 3300X 4-Core Processor
    Memory: 1.71 GB / 15.58 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.15.0 - /usr/bin/npm
  Browsers:
    Brave Browser: unknown
    Firefox: 89.0

**Comment by jpesce** [comment] 2021-06-11 21:22
Reproducible also on mobile (iOS and Android)

https://user-images.githubusercontent.com/1228352/121749958-ded6bf00-cae1-11eb-8b2c-84ae89b66427.mp4

**Comment by IvanClementino** [comment] 2021-06-15 13:04
![image](https://user-images.githubusercontent.com/71457970/122057393-f69f9300-cdc0-11eb-863b-4aacdad3023b.png)
Cliente se referindo a migração do site CMS para IO

**Comment by IvanClementino** [comment] 2021-06-15 14:34
Couldn't reproduce on websites that do not use "api.biggylabs.com.br" like storetheme. Is this related to intelligent search?

**Comment by igorbrasileiro** [comment] 2021-09-29 18:26
Yeah, we tried to fix this problem via these PRs:
https://github.com/vtex-apps/add-to-cart-button/pull/92
https://github.com/vtex-apps/product-context/pull/61
https://github.com/vtex-apps/store-components/pull/967

The problem still happening? The problem isn't related to the biggylabs api, it use to happens, because the product-context updates the `selectedItem` when the skuId query changes and this solution is a little bit slow. So, when you change the sku item and click the add cart too fast, the product still has the old selected item.

**Comment by igorbrasileiro** [comment] 2021-09-29 18:27
I will close this issue because it seems to be already solved but feel free to reopen it.

**Closed by igorbrasileiro** 2021-09-29 18:27 UTC
Labels: bug
