### ISSUE TITLE
SKU variation does not get selected by default on change

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#244] opened 2020-03-24 19:05 UTC
**Describe the bug**
One sku selector option is not changing its variations as the other options.

**To Reproduce**
1. Go to https://shop.samsung.com.py/galaxy-s20/p or https://sop18--samsungpy.myvtex.com/galaxy-s20/p 
2. Select the color cosmic black
https://nimb.ws/HNEaA7
Then you will see that "Modelo" nor "Capacidad" variations are selected by default.

**Expected behavior**
The same functionality as the other sku's. Only happens with that color but they're almost the same.
Video: https://www.loom.com/share/9623e44edf7b44a4b5d2848d35295dbf

**Comment by Klynger** [comment] 2020-04-16 20:28
Hi @luizgpriolli , I couldn't reproduce this errors (and the SKU that you shown in the print is not in the page anymore). Could you update the issue again? And sorry for the delay to respond

**Comment by sebaskun98** [comment] 2020-04-29 20:20
@Klynger Hi! I'm working on this project. The client divides all the samsung galaxy s20 with different storage They aren't using the same sku structure. Thank you anyway.

**Comment by Klynger** [comment] 2020-04-29 20:48
So @sebaskun98 is everything fine now?

**Comment by sebaskun98** [comment] 2020-04-29 21:43
I don't how I can reproduce the bug anymore. Because of that change. 
It happens when you have 3 types of variations only.

**Comment by Klynger** [comment] 2020-04-30 13:48
Ok, I'm going to close this issue. If it happens again you can reopen, thx

**Closed by Klynger** 2020-04-30 13:48 UTC
Labels: bug
