### ISSUE TITLE
Page product with error message

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#286] opened 2020-05-05 18:04 UTC
**Describe the bug**

when i click to enter a product i am getting an error message

"Something exploded: operationId = 1fa67be5-6ba9-49e6-9a6f-d1bd60542742"

**To Reproduce**

at home, I click on a product on the shelf to enter the product page

**Expected behavior**

open the product page

**Screenshots**
![image](https://user-images.githubusercontent.com/4852136/81099665-a7124680-8ee1-11ea-9568-e695c7b3dd20.png)

**Additional context**
account : modaoriginal
workspace : acostamento

**Comment by jorgerubik** [comment] 2020-05-05 19:21
I had the same error but it was solved, do you use many svg / images on your site?

**Comment by alextalha** [comment] 2020-05-05 19:37
yes, i need to use some svg's via css

**Comment by klzns** [comment] 2020-05-05 21:21
Fixed on our end. We'll fix this issue from happening again this week.

**Comment by alexdinca** [comment] 2020-05-06 12:03
> Fixed on our end. We'll fix this issue from happening again this week.

Does this mean that it shouldn't be reproducing anymore?
I'm also facing this issue. 
The search page doesn't work either..

**Comment by klzns** [comment] 2020-05-06 17:50
@alexdinca what is the account?

**Comment by alexdinca** [comment] 2020-05-06 19:20
> @alexdinca what is the account?

veranda.myvtex.com and I'm working on `dev` workspace

**Comment by alextalha** [comment] 2020-05-08 21:41
@klzns  

the problem returned. the product page now opens and the product not found. but the product exists

![image](https://user-images.githubusercontent.com/4852136/81451740-82290800-915b-11ea-9873-ec3fd7112691.png)

**Comment by klzns** [comment] 2020-05-11 13:24
@alextalha I can't reproduce the issue anymore. I guess it's fixed.

**Comment by alextalha** [comment] 2020-05-11 18:26
again @klzns . 

Something exploded: operationId=00af1739-ca39-4319-aa77-ee448cb90bee

url :  https://acostamento--modaoriginal.myvtex.com/terno/p

**Comment by alextalha** [comment] 2020-05-11 18:32
{
code: "route_map_error",
message: "Error fetching source data for route map: Error listing workspace dependencies: (500 generic_error at http://infra.io.vtex.com/apps/v0/modaoriginal/acostamento/v2/apps?fields=_resolvedDependencies%2Cregistry%2Clink%2Cvendor%2Cname%2Cversion%2CcredentialType%2C_isRoot%2C_activationDate) Error listing workspace dependencies: Failed to insert links in workspace dependencies: vtex.store-theme@3.35.0+build1589221294: vtex.countdown@0.x: Failed to list versions and states by timestamp for vtex.countdown: App not published: vtex.countdown",
requestId: "44010d80d86a4cb684a77d3f59a3bbca"
}

**Comment by alextalha** [comment] 2020-05-11 18:35
in terminal 
``
$ vtex link
15:34:28.862 - info: Failed to check for pinned dependencies  
15:34:28.875 - info: Linking app vtex.store-theme@3.35.0  
15:34:29.016 - info: Sending 105 files   
15:34:29.023 - info: Project size: 4.19MB  
15:34:29.024 - info: Compressing project files...
15:34:29.297 - info: Compressed project size: 3.07MB  
15:34:32.667 - info: Retrying...1  
15:34:32.668 - info: Project size: 4.19MB  
15:34:32.668 - info: Compressing project files...
15:34:32.854 - info: Compressed project size: 3.07MB  
15:34:39.925 - info: Retrying...2
15:34:39.926 - info: Project size: 4.19MB
15:34:39.926 - info: Compressing project files...
15:34:40.108 - info: Compressed project size: 3.07MB
15:34:45.041 - error: API: 404 Not Found
15:34:45.042 - error: Source: https://app.io.vtex.com/vtex.builder-hub/v0/modaoriginal/acostamento/_v/builder/0/link/vtex.store-theme@3.35.0
15:34:45.042 - error: Method: post
15:34:45.043 - error: Message: (404 app_not_found at http://infra.io.vtex.com/apps/v0/modaoriginal/acostamento/apps/vtex.builder-hub@0.248.0) Failed to insert links in workspace dependencies: vtex.store-theme@3.35.0+build1589221294: vtex.countdown@0.x: Failed to list versions and states by timestamp for vtex.countdown: App not published: vtex.countdown
15:34:45.047 - error: ErrorID: 2a5a1ed4269fdeef``

**Comment by alextalha** [comment] 2020-05-11 18:45
home don't open anymore too
[error-home.txt](https://github.com/vtex-apps/store-discussion/files/4611441/error-home.txt)

**Closed** 2020-11-18 21:07 UTC
Labels: bug

**Comment by JoKenPo** [comment] 2021-08-24 23:11
I am suffering from the same problem. 
Does anyone have the solution?

**Comment by feervalero** [comment] 2021-09-08 17:01
Hello

Anyone have the solution for this?

Thanks.

**Comment by vaasung** [comment] 2021-09-22 22:34
I am also facing this issue. is any solution?

**Comment by JackVartanian** [comment] 2021-10-07 21:38
I also need some help on this issue.

Does anyone have a solution? Thanks

**Comment by JoKenPo** [comment] 2021-10-08 12:30
I needed to open a ticket in VTEX support.

**Comment by feervalero** [comment] 2021-10-13 20:13
Open a ticket with vtex and ask them to configure the "tenant" in your account.

That worked for me...
