### ISSUE TITLE
Filter Clean Button

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#104] opened 2019-09-09 14:09 UTC
**Is your feature request related to a problem? Please describe.**
I need a button to clean the filter on the department page. This button would work to clean the entire filter.

**Describe the solution you'd like**
I would like that as soon as the button was clicked it would clear the entire filter.

![Captura de Tela 2019-09-09 às 11 07 41](https://user-images.githubusercontent.com/44183746/64537951-24a19a80-d2f2-11e9-8564-bdcc407c96bf.png)

**Comment by denisebiscaro** [comment] 2019-09-11 22:20
Duplicate of #2

**Closed by denisebiscaro** 2019-09-11 22:20 UTC
Labels: feature-request

**Comment by kaibrockelt** [comment] 2021-12-17 13:00
Issue #2 doesnt exist no more (not accessible) - has this feature  been implemented or refused?
