### ISSUE TITLE
Getting INTERNAL_SERVER_ERROR while implementing list-context.product-list

### ISSUE THREAD

**Issue by arielapaula** [vtex-apps/store-discussion#563] opened 2021-03-27 20:22 UTC
**Describe the bug**
I am getting a 400 error while implementing the product-list-context that says that the store is not active.

**To Reproduce**
1. Add the dependencies in the manifest
2. call the block in the home.json:
`
  "store.home": {
    "blocks": [
      "list-context.image-list#home",
      "list-context.product-list#demo1",
      "flex-layout.row#promotional-info",
      "flex-layout.row#banner-home",
      "flex-layout.row#banner-brands",
      "flex-layout.row#newsletter"
    ]
  },`

2. Declare the block in the shelf.jsonc:
`{
  "product-summary.shelf#demo1": {
    "children": [
      "product-summary-name",
      "product-rating-inline",
      "product-summary-space",
      "product-summary-price",
      "product-summary-buy-button"
    ]
  },
  "list-context.product-list#demo1": {
    "blocks": [
      "product-summary.shelf#demo1"
    ],
    "children": [
      "slider-layout#demo-products"
    ],
    "props": {
      "category": "2"
    }
  },
  "slider-layout#demo-products": {
    "props": {
      "itemsPerPage": {
        "desktop": 1,
        "tablet": 1,
        "phone": 1
      },
      "blockClass": "shelf-container"
    }
  }
}`

**Expected behavior**
A shelf on related products

**Screenshots**
![image](https://user-images.githubusercontent.com/36748003/112733835-f65dcd00-8f20-11eb-8b47-bb43170c6ef6.png)

**Comment by klzns** [comment] 2021-03-29 14:31
Duplicate of #562

**Closed by klzns** 2021-03-29 14:31 UTC
Labels: bug
